
#include "nuitka/prelude.hpp"

// Sentinel PyObject to be used for all our call iterator endings. It will become
// a PyCObject pointing to NULL. It's address is unique, and that's enough.
PyObject *_sentinel_value = NULL;

PyCodeObject *_codeobj_fe7e41cf266be56a879b1d02a7f026a8;
PyCodeObject *_codeobj_ba0bc878ff42bb0f15a64e2407dc4f08;
PyCodeObject *_codeobj_1961af640a37b5a9e63e79fa65d67be9;
PyCodeObject *_codeobj_3e0fa4d2fceab70f6822bef546f42175;
PyCodeObject *_codeobj_40348a611a8c2703d2930d6da816052a;
PyCodeObject *_codeobj_ba87d533bce20217ef5367f5d61b1b25;
PyCodeObject *_codeobj_a950acda6ae899b07047749eb8237768;
PyCodeObject *_codeobj_4cdfcb35486aaeb95489f4f5567bfe06;
PyCodeObject *_codeobj_2a7b5c2d688e14d56a1fba9bab6f2fd3;
PyCodeObject *_codeobj_45cd8c1e4bb0fefdb4a0a47611fe6ff6;
PyCodeObject *_codeobj_40b7b0914b4ec885000d16eaf40a8831;
PyCodeObject *_codeobj_5113f53d5a63400bc8d0611429b000e5;
PyCodeObject *_codeobj_db705fa97cb027949eedf47e30a83952;
PyCodeObject *_codeobj_9dc3f027de29dc0cbf7b850431438629;
PyCodeObject *_codeobj_3043f609e2dd0a0c732273b02113e78a;
PyObject *_python_int_0;
PyObject *_python_float_0_0;
PyObject *_python_float_1_0;
PyObject *_python_int_neg_1;
PyObject *_python_int_pos_1;
PyObject *_python_int_pos_2;
PyObject *_python_str_empty;
PyObject *_python_dict_empty;
PyObject *_python_str_plain_f;
PyObject *_python_str_plain_i;
PyObject *_python_str_plain_j;
PyObject *_python_str_plain_l;
PyObject *_python_str_plain_x;
PyObject *_python_tuple_empty;
PyObject *_python_str_plain_d1;
PyObject *_python_str_plain_d2;
PyObject *_python_str_plain_np;
PyObject *_python_str_plain_rb;
PyObject *_python_str_plain_rc;
PyObject *_python_int_pos_20000;
PyObject *_python_str_plain_avg;
PyObject *_python_str_plain_gca;
PyObject *_python_str_plain_idx;
PyObject *_python_str_plain_int;
PyObject *_python_str_plain_key;
PyObject *_python_str_plain_len;
PyObject *_python_str_plain_mid;
PyObject *_python_str_plain_min;
PyObject *_python_str_plain_plt;
PyObject *_python_str_plain_res;
PyObject *_python_str_plain_sig;
PyObject *_python_str_plain_sum;
PyObject *_python_int_neg_500000;
PyObject *_python_int_pos_400000;
PyObject *_python_int_pos_500000;
PyObject *_python_str_plain_args;
PyObject *_python_str_plain_chrX;
PyObject *_python_str_plain_dict;
PyObject *_python_str_plain_font;
PyObject *_python_str_plain_iter;
PyObject *_python_str_plain_izip;
PyObject *_python_str_plain_keys;
PyObject *_python_str_plain_log2;
PyObject *_python_str_plain_long;
PyObject *_python_str_plain_main;
PyObject *_python_str_plain_norm;
PyObject *_python_str_plain_open;
PyObject *_python_str_plain_opts;
PyObject *_python_str_plain_plot;
PyObject *_python_str_plain_read;
PyObject *_python_str_plain_repr;
PyObject *_python_str_plain_self;
PyObject *_python_str_plain_show;
PyObject *_python_str_plain_stop;
PyObject *_python_str_plain_toks;
PyObject *_python_str_plain_type;
PyObject *_python_str_plain_vals;
PyObject *_python_str_plain_chrom;
PyObject *_python_str_plain_dlist;
PyObject *_python_str_plain_feats;
PyObject *_python_str_plain_flist;
PyObject *_python_str_plain_ifile;
PyObject *_python_str_plain_numpy;
PyObject *_python_str_plain_range;
PyObject *_python_str_plain_scipy;
PyObject *_python_str_plain_shape;
PyObject *_python_str_plain_split;
PyObject *_python_str_plain_start;
PyObject *_python_str_plain_strip;
PyObject *_python_str_plain_trapz;
PyObject *_python_str_plain_value;
PyObject *_python_str_plain_winUp;
PyObject *_python_str_plain_yaxis;
PyObject *_python_str_plain_zeros;
PyObject *_python_str_angle_lambda;
PyObject *_python_str_angle_module;
PyObject *_python_str_plain_Domain;
PyObject *_python_str_plain_append;
PyObject *_python_str_plain_called;
PyObject *_python_str_plain_center;
PyObject *_python_str_plain_docopt;
PyObject *_python_str_plain_format;
PyObject *_python_str_plain_isPeak;
PyObject *_python_str_plain_maxIdx;
PyObject *_python_str_plain_object;
PyObject *_python_str_plain_pyplot;
PyObject *_python_str_plain_random;
PyObject *_python_str_plain_rstrip;
PyObject *_python_str_plain_sigLen;
PyObject *_python_str_plain_signal;
PyObject *_python_str_plain_sorted;
PyObject *_python_str_plain_ticker;
PyObject *_python_str_plain_value2;
PyObject *_python_str_plain_xrange;
PyObject *_python_str_plain_xticks;
PyObject *_python_str_plain_ylabel;
PyObject *_python_str_plain___all__;
PyObject *_python_str_plain___doc__;
PyObject *_python_str_plain_avgVals;
PyObject *_python_str_plain_compile;
PyObject *_python_str_plain_domains;
PyObject *_python_str_plain_groupby;
PyObject *_python_str_plain_halfRes;
PyObject *_python_str_plain_inspect;
PyObject *_python_str_plain_valsInp;
PyObject *_python_str_plain_winDown;
PyObject *_python_str_plain_Features;
PyObject *_python_str_plain___dict__;
PyObject *_python_str_plain___exit__;
PyObject *_python_str_plain___file__;
PyObject *_python_str_plain___init__;
PyObject *_python_str_plain___main__;
PyObject *_python_str_plain___name__;
PyObject *_python_str_plain_exc_type;
PyObject *_python_str_plain_parseWig;
PyObject *_python_str_plain___class__;
PyObject *_python_str_plain___enter__;
PyObject *_python_str_plain_exc_value;
PyObject *_python_str_plain_integrate;
PyObject *_python_str_plain_itertools;
PyObject *_python_str_plain___import__;
PyObject *_python_str_plain___iterator;
PyObject *_python_str_plain___module__;
PyObject *_python_str_plain_allDomains;
PyObject *_python_str_plain_isBoundary;
PyObject *_python_str_plain_matplotlib;
PyObject *_python_str_plain_numDomains;
PyObject *_python_str_plain_MaxNLocator;
PyObject *_python_str_plain___delattr__;
PyObject *_python_str_plain___getattr__;
PyObject *_python_str_plain___setattr__;
PyObject *_python_str_plain_lastFeatPos;
PyObject *_python_str_plain_sampleRatio;
PyObject *_python_str_plain___builtins__;
PyObject *_python_str_plain___internal__;
PyObject *_python_str_plain_domainBuffer;
PyObject *_python_str_plain_firstFeatPos;
PyObject *_python_str_plain_isValidLocus;
PyObject *_python_str_plain_processPeaks;
PyObject *_python_str_plain___metaclass__;
PyObject *_python_str_plain_exc_traceback;
PyObject *_python_str_plain_numPlotPoints;
PyObject *_python_str_plain_numWinsCenter;
PyObject *_python_str_plain_processSignal;
PyObject *_python_str_plain_star_arg_dict;
PyObject *_python_tuple_int_0_int_0_tuple;
PyObject *_python_tuple_str_plain_l_tuple;
PyObject *_python_tuple_str_plain_x_tuple;
PyObject *_python_str_plain_areaDifference;
PyObject *_python_str_plain_numControlPeaks;
PyObject *_python_str_plain_numTotalDomains;
PyObject *_python_list_str_plain_docopt_list;
PyObject *_python_list_str_plain_pyplot_list;
PyObject *_python_str_plain_boundaryMidpoint;
PyObject *_python_str_plain_domainPlotPoints;
PyObject *_python_str_plain_windowSumsCenter;
PyObject *_python_tuple_none_none_none_tuple;
PyObject *_python_tuple_str_plain_font_tuple;
PyObject *_python_tuple_str_plain_opts_tuple;
PyObject *_python_tuple_str_plain_self_tuple;
PyObject *_python_str_plain_set_major_locator;
PyObject *_python_tuple_int_pos_1000000_tuple;
PyObject *_python_str_plain_boundaryPlotPoints;
PyObject *_python_str_plain_interDomainLengths;
PyObject *_python_str_plain_numWindowsBoundary;
PyObject *_python_str_plain_windowSumsBoundary;
PyObject *_python_str_plain_broadPeakFileParser;
PyObject *_python_str_plain_areaUnderDomainSignal;
PyObject *_python_str_plain_areaUnderBoundarySignal;
PyObject *_python_dict_545204919ac8f630f464787793212a65;
PyObject *_python_dict_750d4f380d4ab83aa8add2cfc1a6dbba;
PyObject *_python_dict_9cc58b1859648755d276d5241d90b6bc;
PyObject *_python_dict_cd1e41bbb36b492f0ffb5128d92630c6;
PyObject *_python_tuple_str_plain_d1_str_plain_d2_tuple;
PyObject *_python_tuple_str_plain_self_str_plain_l_tuple;
PyObject *_python_list_8aacf1c2ae7752a942c743c3422bf66c_list;
PyObject *_python_str_digest_04d542fe40e298e5929a23f3bb806b3d;
PyObject *_python_str_digest_243c29181f959f17ead3e6a1c0b9426e;
PyObject *_python_str_digest_268060527bc6c0022bb231d71f93eb88;
PyObject *_python_str_digest_2b80eb31c34b6db78f73a2928093f163;
PyObject *_python_str_digest_3451707491a177b52280801d2b61e76a;
PyObject *_python_str_digest_56fab43f67e3a144c4d65d8595f362a1;
PyObject *_python_str_digest_6db5b7658154875cb20ec23242e200d6;
PyObject *_python_str_digest_6f69449e3cbe19d8aaa066664eccb812;
PyObject *_python_str_digest_70e6205803ec3c66a2fdd2c934f08873;
PyObject *_python_str_digest_7c29a05f8728cfc364cfd2f00df53fff;
PyObject *_python_str_digest_840934ca10eeab23946338186a862e96;
PyObject *_python_str_digest_bcd8b0c2eb1fce714eab6cef0d771acc;
PyObject *_python_str_digest_c33694c72d824dd28bdac36ec81a5e8c;
PyObject *_python_str_digest_d98f321d05a4cbcb8d879727b9d89c5f;
PyObject *_python_str_digest_dbdf9e465e56b8046daa1d64216bffac;
PyObject *_python_str_digest_f7bf55962e9d56c800705431462f3a10;
PyObject *_python_tuple_e761227227b13b15ac8c8322d0c6e13d_tuple;
PyObject *_python_tuple_str_digest_2e953ccbf738085588fd0a483a12c808_tuple;
static PyObject *_python_int_pos_4;
static PyObject *_python_int_pos_18;
static PyObject *_python_str_plain_size;
static PyObject *_python_int_pos_1000000;
static PyObject *_python_str_plain_500kb;
static PyObject *_python_str_plain_lower;
static PyObject *_python_str_plain_prune;
static PyObject *_python_str_plain_family;
static PyObject *_python_str_plain_normal;
static PyObject *_python_str_plain_version;
static PyObject *_python_str_plain_boundary;
static PyObject *_python_str_plain_linewidth;
static PyObject *_python_str_digest_254062843c0e085a132a317e8fd01cfe;
static PyObject *_python_str_digest_2e953ccbf738085588fd0a483a12c808;
static PyObject *_python_str_digest_627e18dd6704830f021195cb66d554d8;

static void __initConstants( void )
{
    if ( false )
    {
        UNSTREAM_INIT();
    }

    _python_int_0 = PyInt_FromLong( 0 );
    _python_float_0_0 = UNSTREAM_FLOAT( "\0\0\0\0\0\0\0\0" );
    _python_float_1_0 = UNSTREAM_FLOAT( "\0\0\0\0\0\0\360\77" );
    _python_int_neg_1 = PyInt_FromLong( -1 );
    _python_int_pos_1 = PyInt_FromLong( 1 );
    _python_int_pos_2 = PyInt_FromLong( 2 );
    _python_int_pos_4 = PyInt_FromLong( 4 );
    _python_str_empty = UNSTREAM_STRING( "", 0, 0 );assert( _python_str_empty );
    _python_dict_empty = PyDict_New();
    _python_int_pos_18 = PyInt_FromLong( 18 );
    _python_str_plain_f = UNSTREAM_STRING( "f", 1, 1 );assert( _python_str_plain_f );
    _python_str_plain_i = UNSTREAM_STRING( "i", 1, 1 );assert( _python_str_plain_i );
    _python_str_plain_j = UNSTREAM_STRING( "j", 1, 1 );assert( _python_str_plain_j );
    _python_str_plain_l = UNSTREAM_STRING( "l", 1, 1 );assert( _python_str_plain_l );
    _python_str_plain_x = UNSTREAM_STRING( "x", 1, 1 );assert( _python_str_plain_x );
    _python_tuple_empty = PyTuple_New( 0 );
    _python_str_plain_d1 = UNSTREAM_STRING( "d1", 2, 1 );assert( _python_str_plain_d1 );
    _python_str_plain_d2 = UNSTREAM_STRING( "d2", 2, 1 );assert( _python_str_plain_d2 );
    _python_str_plain_np = UNSTREAM_STRING( "np", 2, 1 );assert( _python_str_plain_np );
    _python_str_plain_rb = UNSTREAM_STRING( "rb", 2, 1 );assert( _python_str_plain_rb );
    _python_str_plain_rc = UNSTREAM_STRING( "rc", 2, 1 );assert( _python_str_plain_rc );
    _python_int_pos_20000 = PyInt_FromLong( 20000 );
    _python_str_plain_avg = UNSTREAM_STRING( "avg", 3, 1 );assert( _python_str_plain_avg );
    _python_str_plain_gca = UNSTREAM_STRING( "gca", 3, 1 );assert( _python_str_plain_gca );
    _python_str_plain_idx = UNSTREAM_STRING( "idx", 3, 1 );assert( _python_str_plain_idx );
    _python_str_plain_int = UNSTREAM_STRING( "int", 3, 1 );assert( _python_str_plain_int );
    _python_str_plain_key = UNSTREAM_STRING( "key", 3, 1 );assert( _python_str_plain_key );
    _python_str_plain_len = UNSTREAM_STRING( "len", 3, 1 );assert( _python_str_plain_len );
    _python_str_plain_mid = UNSTREAM_STRING( "mid", 3, 1 );assert( _python_str_plain_mid );
    _python_str_plain_min = UNSTREAM_STRING( "min", 3, 1 );assert( _python_str_plain_min );
    _python_str_plain_plt = UNSTREAM_STRING( "plt", 3, 1 );assert( _python_str_plain_plt );
    _python_str_plain_res = UNSTREAM_STRING( "res", 3, 1 );assert( _python_str_plain_res );
    _python_str_plain_sig = UNSTREAM_STRING( "sig", 3, 1 );assert( _python_str_plain_sig );
    _python_str_plain_sum = UNSTREAM_STRING( "sum", 3, 1 );assert( _python_str_plain_sum );
    _python_int_neg_500000 = PyInt_FromLong( -500000 );
    _python_int_pos_400000 = PyInt_FromLong( 400000 );
    _python_int_pos_500000 = PyInt_FromLong( 500000 );
    _python_str_plain_args = UNSTREAM_STRING( "args", 4, 1 );assert( _python_str_plain_args );
    _python_str_plain_chrX = UNSTREAM_STRING( "chrX", 4, 1 );assert( _python_str_plain_chrX );
    _python_str_plain_dict = UNSTREAM_STRING( "dict", 4, 1 );assert( _python_str_plain_dict );
    _python_str_plain_font = UNSTREAM_STRING( "font", 4, 1 );assert( _python_str_plain_font );
    _python_str_plain_iter = UNSTREAM_STRING( "iter", 4, 1 );assert( _python_str_plain_iter );
    _python_str_plain_izip = UNSTREAM_STRING( "izip", 4, 1 );assert( _python_str_plain_izip );
    _python_str_plain_keys = UNSTREAM_STRING( "keys", 4, 1 );assert( _python_str_plain_keys );
    _python_str_plain_log2 = UNSTREAM_STRING( "log2", 4, 1 );assert( _python_str_plain_log2 );
    _python_str_plain_long = UNSTREAM_STRING( "long", 4, 1 );assert( _python_str_plain_long );
    _python_str_plain_main = UNSTREAM_STRING( "main", 4, 1 );assert( _python_str_plain_main );
    _python_str_plain_norm = UNSTREAM_STRING( "norm", 4, 1 );assert( _python_str_plain_norm );
    _python_str_plain_open = UNSTREAM_STRING( "open", 4, 1 );assert( _python_str_plain_open );
    _python_str_plain_opts = UNSTREAM_STRING( "opts", 4, 1 );assert( _python_str_plain_opts );
    _python_str_plain_plot = UNSTREAM_STRING( "plot", 4, 1 );assert( _python_str_plain_plot );
    _python_str_plain_read = UNSTREAM_STRING( "read", 4, 1 );assert( _python_str_plain_read );
    _python_str_plain_repr = UNSTREAM_STRING( "repr", 4, 1 );assert( _python_str_plain_repr );
    _python_str_plain_self = UNSTREAM_STRING( "self", 4, 1 );assert( _python_str_plain_self );
    _python_str_plain_show = UNSTREAM_STRING( "show", 4, 1 );assert( _python_str_plain_show );
    _python_str_plain_size = UNSTREAM_STRING( "size", 4, 1 );assert( _python_str_plain_size );
    _python_str_plain_stop = UNSTREAM_STRING( "stop", 4, 1 );assert( _python_str_plain_stop );
    _python_str_plain_toks = UNSTREAM_STRING( "toks", 4, 1 );assert( _python_str_plain_toks );
    _python_str_plain_type = UNSTREAM_STRING( "type", 4, 1 );assert( _python_str_plain_type );
    _python_str_plain_vals = UNSTREAM_STRING( "vals", 4, 1 );assert( _python_str_plain_vals );
    _python_int_pos_1000000 = PyInt_FromLong( 1000000 );
    _python_str_plain_500kb = UNSTREAM_STRING( "500kb", 5, 0 );assert( _python_str_plain_500kb );
    _python_str_plain_chrom = UNSTREAM_STRING( "chrom", 5, 1 );assert( _python_str_plain_chrom );
    _python_str_plain_dlist = UNSTREAM_STRING( "dlist", 5, 1 );assert( _python_str_plain_dlist );
    _python_str_plain_feats = UNSTREAM_STRING( "feats", 5, 1 );assert( _python_str_plain_feats );
    _python_str_plain_flist = UNSTREAM_STRING( "flist", 5, 1 );assert( _python_str_plain_flist );
    _python_str_plain_ifile = UNSTREAM_STRING( "ifile", 5, 1 );assert( _python_str_plain_ifile );
    _python_str_plain_lower = UNSTREAM_STRING( "lower", 5, 1 );assert( _python_str_plain_lower );
    _python_str_plain_numpy = UNSTREAM_STRING( "numpy", 5, 1 );assert( _python_str_plain_numpy );
    _python_str_plain_prune = UNSTREAM_STRING( "prune", 5, 1 );assert( _python_str_plain_prune );
    _python_str_plain_range = UNSTREAM_STRING( "range", 5, 1 );assert( _python_str_plain_range );
    _python_str_plain_scipy = UNSTREAM_STRING( "scipy", 5, 1 );assert( _python_str_plain_scipy );
    _python_str_plain_shape = UNSTREAM_STRING( "shape", 5, 1 );assert( _python_str_plain_shape );
    _python_str_plain_split = UNSTREAM_STRING( "split", 5, 1 );assert( _python_str_plain_split );
    _python_str_plain_start = UNSTREAM_STRING( "start", 5, 1 );assert( _python_str_plain_start );
    _python_str_plain_strip = UNSTREAM_STRING( "strip", 5, 1 );assert( _python_str_plain_strip );
    _python_str_plain_trapz = UNSTREAM_STRING( "trapz", 5, 1 );assert( _python_str_plain_trapz );
    _python_str_plain_value = UNSTREAM_STRING( "value", 5, 1 );assert( _python_str_plain_value );
    _python_str_plain_winUp = UNSTREAM_STRING( "winUp", 5, 1 );assert( _python_str_plain_winUp );
    _python_str_plain_yaxis = UNSTREAM_STRING( "yaxis", 5, 1 );assert( _python_str_plain_yaxis );
    _python_str_plain_zeros = UNSTREAM_STRING( "zeros", 5, 1 );assert( _python_str_plain_zeros );
    _python_str_angle_lambda = UNSTREAM_STRING( "<lambda>", 8, 0 );assert( _python_str_angle_lambda );
    _python_str_angle_module = UNSTREAM_STRING( "<module>", 8, 0 );assert( _python_str_angle_module );
    _python_str_plain_Domain = UNSTREAM_STRING( "Domain", 6, 1 );assert( _python_str_plain_Domain );
    _python_str_plain_append = UNSTREAM_STRING( "append", 6, 1 );assert( _python_str_plain_append );
    _python_str_plain_called = UNSTREAM_STRING( "called", 6, 1 );assert( _python_str_plain_called );
    _python_str_plain_center = UNSTREAM_STRING( "center", 6, 1 );assert( _python_str_plain_center );
    _python_str_plain_docopt = UNSTREAM_STRING( "docopt", 6, 1 );assert( _python_str_plain_docopt );
    _python_str_plain_family = UNSTREAM_STRING( "family", 6, 1 );assert( _python_str_plain_family );
    _python_str_plain_format = UNSTREAM_STRING( "format", 6, 1 );assert( _python_str_plain_format );
    _python_str_plain_isPeak = UNSTREAM_STRING( "isPeak", 6, 1 );assert( _python_str_plain_isPeak );
    _python_str_plain_maxIdx = UNSTREAM_STRING( "maxIdx", 6, 1 );assert( _python_str_plain_maxIdx );
    _python_str_plain_normal = UNSTREAM_STRING( "normal", 6, 1 );assert( _python_str_plain_normal );
    _python_str_plain_object = UNSTREAM_STRING( "object", 6, 1 );assert( _python_str_plain_object );
    _python_str_plain_pyplot = UNSTREAM_STRING( "pyplot", 6, 1 );assert( _python_str_plain_pyplot );
    _python_str_plain_random = UNSTREAM_STRING( "random", 6, 1 );assert( _python_str_plain_random );
    _python_str_plain_rstrip = UNSTREAM_STRING( "rstrip", 6, 1 );assert( _python_str_plain_rstrip );
    _python_str_plain_sigLen = UNSTREAM_STRING( "sigLen", 6, 1 );assert( _python_str_plain_sigLen );
    _python_str_plain_signal = UNSTREAM_STRING( "signal", 6, 1 );assert( _python_str_plain_signal );
    _python_str_plain_sorted = UNSTREAM_STRING( "sorted", 6, 1 );assert( _python_str_plain_sorted );
    _python_str_plain_ticker = UNSTREAM_STRING( "ticker", 6, 1 );assert( _python_str_plain_ticker );
    _python_str_plain_value2 = UNSTREAM_STRING( "value2", 6, 1 );assert( _python_str_plain_value2 );
    _python_str_plain_xrange = UNSTREAM_STRING( "xrange", 6, 1 );assert( _python_str_plain_xrange );
    _python_str_plain_xticks = UNSTREAM_STRING( "xticks", 6, 1 );assert( _python_str_plain_xticks );
    _python_str_plain_ylabel = UNSTREAM_STRING( "ylabel", 6, 1 );assert( _python_str_plain_ylabel );
    _python_str_plain___all__ = UNSTREAM_STRING( "__all__", 7, 1 );assert( _python_str_plain___all__ );
    _python_str_plain___doc__ = UNSTREAM_STRING( "__doc__", 7, 1 );assert( _python_str_plain___doc__ );
    _python_str_plain_avgVals = UNSTREAM_STRING( "avgVals", 7, 1 );assert( _python_str_plain_avgVals );
    _python_str_plain_compile = UNSTREAM_STRING( "compile", 7, 1 );assert( _python_str_plain_compile );
    _python_str_plain_domains = UNSTREAM_STRING( "domains", 7, 1 );assert( _python_str_plain_domains );
    _python_str_plain_groupby = UNSTREAM_STRING( "groupby", 7, 1 );assert( _python_str_plain_groupby );
    _python_str_plain_halfRes = UNSTREAM_STRING( "halfRes", 7, 1 );assert( _python_str_plain_halfRes );
    _python_str_plain_inspect = UNSTREAM_STRING( "inspect", 7, 1 );assert( _python_str_plain_inspect );
    _python_str_plain_valsInp = UNSTREAM_STRING( "valsInp", 7, 1 );assert( _python_str_plain_valsInp );
    _python_str_plain_version = UNSTREAM_STRING( "version", 7, 1 );assert( _python_str_plain_version );
    _python_str_plain_winDown = UNSTREAM_STRING( "winDown", 7, 1 );assert( _python_str_plain_winDown );
    _python_str_plain_Features = UNSTREAM_STRING( "Features", 8, 1 );assert( _python_str_plain_Features );
    _python_str_plain___dict__ = UNSTREAM_STRING( "__dict__", 8, 1 );assert( _python_str_plain___dict__ );
    _python_str_plain___exit__ = UNSTREAM_STRING( "__exit__", 8, 1 );assert( _python_str_plain___exit__ );
    _python_str_plain___file__ = UNSTREAM_STRING( "__file__", 8, 1 );assert( _python_str_plain___file__ );
    _python_str_plain___init__ = UNSTREAM_STRING( "__init__", 8, 1 );assert( _python_str_plain___init__ );
    _python_str_plain___main__ = UNSTREAM_STRING( "__main__", 8, 1 );assert( _python_str_plain___main__ );
    _python_str_plain___name__ = UNSTREAM_STRING( "__name__", 8, 1 );assert( _python_str_plain___name__ );
    _python_str_plain_boundary = UNSTREAM_STRING( "boundary", 8, 1 );assert( _python_str_plain_boundary );
    _python_str_plain_exc_type = UNSTREAM_STRING( "exc_type", 8, 1 );assert( _python_str_plain_exc_type );
    _python_str_plain_parseWig = UNSTREAM_STRING( "parseWig", 8, 1 );assert( _python_str_plain_parseWig );
    _python_str_plain___class__ = UNSTREAM_STRING( "__class__", 9, 1 );assert( _python_str_plain___class__ );
    _python_str_plain___enter__ = UNSTREAM_STRING( "__enter__", 9, 1 );assert( _python_str_plain___enter__ );
    _python_str_plain_exc_value = UNSTREAM_STRING( "exc_value", 9, 1 );assert( _python_str_plain_exc_value );
    _python_str_plain_integrate = UNSTREAM_STRING( "integrate", 9, 1 );assert( _python_str_plain_integrate );
    _python_str_plain_itertools = UNSTREAM_STRING( "itertools", 9, 1 );assert( _python_str_plain_itertools );
    _python_str_plain_linewidth = UNSTREAM_STRING( "linewidth", 9, 1 );assert( _python_str_plain_linewidth );
    _python_str_plain___import__ = UNSTREAM_STRING( "__import__", 10, 1 );assert( _python_str_plain___import__ );
    _python_str_plain___iterator = UNSTREAM_STRING( "__iterator", 10, 1 );assert( _python_str_plain___iterator );
    _python_str_plain___module__ = UNSTREAM_STRING( "__module__", 10, 1 );assert( _python_str_plain___module__ );
    _python_str_plain_allDomains = UNSTREAM_STRING( "allDomains", 10, 1 );assert( _python_str_plain_allDomains );
    _python_str_plain_isBoundary = UNSTREAM_STRING( "isBoundary", 10, 1 );assert( _python_str_plain_isBoundary );
    _python_str_plain_matplotlib = UNSTREAM_STRING( "matplotlib", 10, 1 );assert( _python_str_plain_matplotlib );
    _python_str_plain_numDomains = UNSTREAM_STRING( "numDomains", 10, 1 );assert( _python_str_plain_numDomains );
    _python_str_plain_MaxNLocator = UNSTREAM_STRING( "MaxNLocator", 11, 1 );assert( _python_str_plain_MaxNLocator );
    _python_str_plain___delattr__ = UNSTREAM_STRING( "__delattr__", 11, 1 );assert( _python_str_plain___delattr__ );
    _python_str_plain___getattr__ = UNSTREAM_STRING( "__getattr__", 11, 1 );assert( _python_str_plain___getattr__ );
    _python_str_plain___setattr__ = UNSTREAM_STRING( "__setattr__", 11, 1 );assert( _python_str_plain___setattr__ );
    _python_str_plain_lastFeatPos = UNSTREAM_STRING( "lastFeatPos", 11, 1 );assert( _python_str_plain_lastFeatPos );
    _python_str_plain_sampleRatio = UNSTREAM_STRING( "sampleRatio", 11, 1 );assert( _python_str_plain_sampleRatio );
    _python_str_plain___builtins__ = UNSTREAM_STRING( "__builtins__", 12, 1 );assert( _python_str_plain___builtins__ );
    _python_str_plain___internal__ = UNSTREAM_STRING( "__internal__", 12, 1 );assert( _python_str_plain___internal__ );
    _python_str_plain_domainBuffer = UNSTREAM_STRING( "domainBuffer", 12, 1 );assert( _python_str_plain_domainBuffer );
    _python_str_plain_firstFeatPos = UNSTREAM_STRING( "firstFeatPos", 12, 1 );assert( _python_str_plain_firstFeatPos );
    _python_str_plain_isValidLocus = UNSTREAM_STRING( "isValidLocus", 12, 1 );assert( _python_str_plain_isValidLocus );
    _python_str_plain_processPeaks = UNSTREAM_STRING( "processPeaks", 12, 1 );assert( _python_str_plain_processPeaks );
    _python_str_plain___metaclass__ = UNSTREAM_STRING( "__metaclass__", 13, 1 );assert( _python_str_plain___metaclass__ );
    _python_str_plain_exc_traceback = UNSTREAM_STRING( "exc_traceback", 13, 1 );assert( _python_str_plain_exc_traceback );
    _python_str_plain_numPlotPoints = UNSTREAM_STRING( "numPlotPoints", 13, 1 );assert( _python_str_plain_numPlotPoints );
    _python_str_plain_numWinsCenter = UNSTREAM_STRING( "numWinsCenter", 13, 1 );assert( _python_str_plain_numWinsCenter );
    _python_str_plain_processSignal = UNSTREAM_STRING( "processSignal", 13, 1 );assert( _python_str_plain_processSignal );
    _python_str_plain_star_arg_dict = UNSTREAM_STRING( "star_arg_dict", 13, 1 );assert( _python_str_plain_star_arg_dict );
    _python_tuple_int_0_int_0_tuple = MAKE_TUPLE2( _python_int_0, _python_int_0 );
    _python_tuple_str_plain_l_tuple = MAKE_TUPLE1( _python_str_plain_l );
    _python_tuple_str_plain_x_tuple = MAKE_TUPLE1( _python_str_plain_x );
    _python_str_plain_areaDifference = UNSTREAM_STRING( "areaDifference", 14, 1 );assert( _python_str_plain_areaDifference );
    _python_str_plain_numControlPeaks = UNSTREAM_STRING( "numControlPeaks", 15, 1 );assert( _python_str_plain_numControlPeaks );
    _python_str_plain_numTotalDomains = UNSTREAM_STRING( "numTotalDomains", 15, 1 );assert( _python_str_plain_numTotalDomains );
    _python_list_str_plain_docopt_list = MAKE_LIST1( _python_str_plain_docopt );
    _python_list_str_plain_pyplot_list = MAKE_LIST1( _python_str_plain_pyplot );
    _python_str_plain_boundaryMidpoint = UNSTREAM_STRING( "boundaryMidpoint", 16, 1 );assert( _python_str_plain_boundaryMidpoint );
    _python_str_plain_domainPlotPoints = UNSTREAM_STRING( "domainPlotPoints", 16, 1 );assert( _python_str_plain_domainPlotPoints );
    _python_str_plain_windowSumsCenter = UNSTREAM_STRING( "windowSumsCenter", 16, 1 );assert( _python_str_plain_windowSumsCenter );
    _python_tuple_none_none_none_tuple = MAKE_TUPLE3( Py_None, Py_None, Py_None );
    _python_tuple_str_plain_font_tuple = MAKE_TUPLE1( _python_str_plain_font );
    _python_tuple_str_plain_opts_tuple = MAKE_TUPLE1( _python_str_plain_opts );
    _python_tuple_str_plain_self_tuple = MAKE_TUPLE1( _python_str_plain_self );
    _python_str_plain_set_major_locator = UNSTREAM_STRING( "set_major_locator", 17, 1 );assert( _python_str_plain_set_major_locator );
    _python_tuple_int_pos_1000000_tuple = MAKE_TUPLE1( _python_int_pos_1000000 );
    _python_str_plain_boundaryPlotPoints = UNSTREAM_STRING( "boundaryPlotPoints", 18, 1 );assert( _python_str_plain_boundaryPlotPoints );
    _python_str_plain_interDomainLengths = UNSTREAM_STRING( "interDomainLengths", 18, 1 );assert( _python_str_plain_interDomainLengths );
    _python_str_plain_numWindowsBoundary = UNSTREAM_STRING( "numWindowsBoundary", 18, 1 );assert( _python_str_plain_numWindowsBoundary );
    _python_str_plain_windowSumsBoundary = UNSTREAM_STRING( "windowSumsBoundary", 18, 1 );assert( _python_str_plain_windowSumsBoundary );
    _python_str_plain_broadPeakFileParser = UNSTREAM_STRING( "broadPeakFileParser", 19, 1 );assert( _python_str_plain_broadPeakFileParser );
    _python_str_plain_areaUnderDomainSignal = UNSTREAM_STRING( "areaUnderDomainSignal", 21, 1 );assert( _python_str_plain_areaUnderDomainSignal );
    _python_str_plain_areaUnderBoundarySignal = UNSTREAM_STRING( "areaUnderBoundarySignal", 23, 1 );assert( _python_str_plain_areaUnderBoundarySignal );
    _python_str_digest_254062843c0e085a132a317e8fd01cfe = UNSTREAM_STRING( "AnalyzeFeatures v1.0", 20, 0 );assert( _python_str_digest_254062843c0e085a132a317e8fd01cfe );
    _python_dict_545204919ac8f630f464787793212a65 = MAKE_DICT1( _python_str_digest_254062843c0e085a132a317e8fd01cfe, _python_str_plain_version );
    _python_dict_750d4f380d4ab83aa8add2cfc1a6dbba = MAKE_DICT1( _python_str_plain_lower, _python_str_plain_prune );
    _python_dict_9cc58b1859648755d276d5241d90b6bc = MAKE_DICT2( _python_str_plain_normal, _python_str_plain_family, _python_int_pos_18, _python_str_plain_size );
    _python_dict_cd1e41bbb36b492f0ffb5128d92630c6 = MAKE_DICT1( _python_int_pos_4, _python_str_plain_linewidth );
    _python_tuple_str_plain_d1_str_plain_d2_tuple = MAKE_TUPLE2( _python_str_plain_d1, _python_str_plain_d2 );
    _python_tuple_str_plain_self_str_plain_l_tuple = MAKE_TUPLE2( _python_str_plain_self, _python_str_plain_l );
    _python_str_digest_627e18dd6704830f021195cb66d554d8 = UNSTREAM_STRING( "-500kb", 6, 0 );assert( _python_str_digest_627e18dd6704830f021195cb66d554d8 );
    _python_list_8aacf1c2ae7752a942c743c3422bf66c_list = MAKE_LIST3( _python_str_digest_627e18dd6704830f021195cb66d554d8, _python_str_plain_boundary, _python_str_plain_500kb );
    _python_str_digest_04d542fe40e298e5929a23f3bb806b3d = UNSTREAM_STRING( " instance", 9, 0 );assert( _python_str_digest_04d542fe40e298e5929a23f3bb806b3d );
    _python_str_digest_243c29181f959f17ead3e6a1c0b9426e = UNSTREAM_STRING( "--peak", 6, 0 );assert( _python_str_digest_243c29181f959f17ead3e6a1c0b9426e );
    _python_str_digest_268060527bc6c0022bb231d71f93eb88 = UNSTREAM_STRING( " object", 7, 0 );assert( _python_str_digest_268060527bc6c0022bb231d71f93eb88 );
    _python_str_digest_2b80eb31c34b6db78f73a2928093f163 = UNSTREAM_STRING( "Processing {}", 13, 0 );assert( _python_str_digest_2b80eb31c34b6db78f73a2928093f163 );
    _python_str_digest_2e953ccbf738085588fd0a483a12c808 = UNSTREAM_STRING( "Average # Peaks per 10kb", 24, 0 );assert( _python_str_digest_2e953ccbf738085588fd0a483a12c808 );
    _python_str_digest_3451707491a177b52280801d2b61e76a = UNSTREAM_STRING( " constructor", 12, 0 );assert( _python_str_digest_3451707491a177b52280801d2b61e76a );
    _python_str_digest_56fab43f67e3a144c4d65d8595f362a1 = UNSTREAM_STRING( "--domains", 9, 0 );assert( _python_str_digest_56fab43f67e3a144c4d65d8595f362a1 );
    _python_str_digest_6db5b7658154875cb20ec23242e200d6 = UNSTREAM_STRING( "AnalyzeFeatures.py", 18, 0 );assert( _python_str_digest_6db5b7658154875cb20ec23242e200d6 );
    _python_str_digest_6f69449e3cbe19d8aaa066664eccb812 = UNSTREAM_STRING( "%s argument after ** must be a mapping, not %s", 46, 0 );assert( _python_str_digest_6f69449e3cbe19d8aaa066664eccb812 );
    _python_str_digest_70e6205803ec3c66a2fdd2c934f08873 = UNSTREAM_STRING( "scipy.integrate", 15, 0 );assert( _python_str_digest_70e6205803ec3c66a2fdd2c934f08873 );
    _python_str_digest_7c29a05f8728cfc364cfd2f00df53fff = UNSTREAM_STRING( "--feature", 9, 0 );assert( _python_str_digest_7c29a05f8728cfc364cfd2f00df53fff );
    _python_str_digest_840934ca10eeab23946338186a862e96 = UNSTREAM_STRING( "--numControlBoundaries", 22, 0 );assert( _python_str_digest_840934ca10eeab23946338186a862e96 );
    _python_str_digest_bcd8b0c2eb1fce714eab6cef0d771acc = UNSTREAM_STRING( "()", 2, 0 );assert( _python_str_digest_bcd8b0c2eb1fce714eab6cef0d771acc );
    _python_str_digest_c33694c72d824dd28bdac36ec81a5e8c = UNSTREAM_STRING( "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python", 102, 0 );assert( _python_str_digest_c33694c72d824dd28bdac36ec81a5e8c );
    _python_str_digest_d98f321d05a4cbcb8d879727b9d89c5f = UNSTREAM_STRING( "\12\12Usage: AnalyzeFeatures.py --domains=<domains> --feature=<feature> --res=<res> [--numControlBoundaries=<nc>] [--peak]\12\12Options:\12  --domains=<domains>            The domains file\12  --feature=<feature>            The feature to plot\12  --res=<res>                    Resolution of the bins [default: 10000]\12  --peak                         Interpret the input as a peak file (instead of signal)\12  --numControlBoundaries=<nc>    Number of control domains (e.g. number of do)\12", 472, 0 );assert( _python_str_digest_d98f321d05a4cbcb8d879727b9d89c5f );
    _python_str_digest_dbdf9e465e56b8046daa1d64216bffac = UNSTREAM_STRING( "areaDifference = {}", 19, 0 );assert( _python_str_digest_dbdf9e465e56b8046daa1d64216bffac );
    _python_str_digest_f7bf55962e9d56c800705431462f3a10 = UNSTREAM_STRING( "--res", 5, 0 );assert( _python_str_digest_f7bf55962e9d56c800705431462f3a10 );
    _python_tuple_e761227227b13b15ac8c8322d0c6e13d_tuple = MAKE_TUPLE4( _python_str_plain_chrom, _python_str_plain_flist, _python_str_plain_domains, _python_str_plain_res );
    _python_tuple_str_digest_2e953ccbf738085588fd0a483a12c808_tuple = MAKE_TUPLE1( _python_str_digest_2e953ccbf738085588fd0a483a12c808 );
    _codeobj_fe7e41cf266be56a879b1d02a7f026a8 = MAKE_CODEOBJ( _python_str_digest_6db5b7658154875cb20ec23242e200d6, _python_str_angle_lambda, 96, _python_tuple_str_plain_x_tuple, 1, CO_NEWLOCALS | CO_OPTIMIZED );
    _codeobj_ba0bc878ff42bb0f15a64e2407dc4f08 = MAKE_CODEOBJ( _python_str_digest_6db5b7658154875cb20ec23242e200d6, _python_str_angle_lambda, 118, _python_tuple_str_plain_x_tuple, 1, CO_NEWLOCALS | CO_OPTIMIZED );
    _codeobj_1961af640a37b5a9e63e79fa65d67be9 = MAKE_CODEOBJ( _python_str_digest_6db5b7658154875cb20ec23242e200d6, _python_str_angle_lambda, 120, _python_tuple_str_plain_x_tuple, 1, CO_NEWLOCALS | CO_OPTIMIZED );
    _codeobj_3e0fa4d2fceab70f6822bef546f42175 = MAKE_CODEOBJ( _python_str_digest_6db5b7658154875cb20ec23242e200d6, _python_str_angle_lambda, 133, _python_tuple_str_plain_x_tuple, 1, CO_NEWLOCALS | CO_OPTIMIZED );
    _codeobj_40348a611a8c2703d2930d6da816052a = MAKE_CODEOBJ( _python_str_digest_6db5b7658154875cb20ec23242e200d6, _python_str_angle_lambda, 141, _python_tuple_str_plain_x_tuple, 1, CO_NEWLOCALS | CO_OPTIMIZED );
    _codeobj_ba87d533bce20217ef5367f5d61b1b25 = MAKE_CODEOBJ( _python_str_digest_6db5b7658154875cb20ec23242e200d6, _python_str_angle_lambda, 142, _python_tuple_str_plain_x_tuple, 1, CO_NEWLOCALS | CO_OPTIMIZED );
    _codeobj_a950acda6ae899b07047749eb8237768 = MAKE_CODEOBJ( _python_str_digest_6db5b7658154875cb20ec23242e200d6, _python_str_angle_module, 0, _python_tuple_empty, 0, 0 );
    _codeobj_4cdfcb35486aaeb95489f4f5567bfe06 = MAKE_CODEOBJ( _python_str_digest_6db5b7658154875cb20ec23242e200d6, _python_str_plain___init__, 21, _python_tuple_str_plain_self_str_plain_l_tuple, 2, CO_NEWLOCALS | CO_OPTIMIZED );
    _codeobj_2a7b5c2d688e14d56a1fba9bab6f2fd3 = MAKE_CODEOBJ( _python_str_digest_6db5b7658154875cb20ec23242e200d6, _python_str_plain_boundaryMidpoint, 155, _python_tuple_str_plain_d1_str_plain_d2_tuple, 2, CO_NEWLOCALS | CO_OPTIMIZED );
    _codeobj_45cd8c1e4bb0fefdb4a0a47611fe6ff6 = MAKE_CODEOBJ( _python_str_digest_6db5b7658154875cb20ec23242e200d6, _python_str_plain_center, 27, _python_tuple_str_plain_self_tuple, 1, CO_NEWLOCALS | CO_OPTIMIZED );
    _codeobj_40b7b0914b4ec885000d16eaf40a8831 = MAKE_CODEOBJ( _python_str_digest_6db5b7658154875cb20ec23242e200d6, _python_str_plain_isBoundary, 152, _python_tuple_str_plain_d1_str_plain_d2_tuple, 2, CO_NEWLOCALS | CO_OPTIMIZED );
    _codeobj_5113f53d5a63400bc8d0611429b000e5 = MAKE_CODEOBJ( _python_str_digest_6db5b7658154875cb20ec23242e200d6, _python_str_plain_isValidLocus, 158, _python_tuple_str_plain_l_tuple, 1, CO_NEWLOCALS | CO_OPTIMIZED );
    _codeobj_db705fa97cb027949eedf47e30a83952 = MAKE_CODEOBJ( _python_str_digest_6db5b7658154875cb20ec23242e200d6, _python_str_plain_main, 88, _python_tuple_str_plain_opts_tuple, 1, CO_NEWLOCALS | CO_OPTIMIZED );
    _codeobj_9dc3f027de29dc0cbf7b850431438629 = MAKE_CODEOBJ( _python_str_digest_6db5b7658154875cb20ec23242e200d6, _python_str_plain_processPeaks, 30, _python_tuple_e761227227b13b15ac8c8322d0c6e13d_tuple, 4, CO_NEWLOCALS | CO_OPTIMIZED );
    _codeobj_3043f609e2dd0a0c732273b02113e78a = MAKE_CODEOBJ( _python_str_digest_6db5b7658154875cb20ec23242e200d6, _python_str_plain_processSignal, 54, _python_tuple_e761227227b13b15ac8c8322d0c6e13d_tuple, 4, CO_NEWLOCALS | CO_OPTIMIZED );
}

void _initConstants( void )
{
    if ( _sentinel_value == NULL )
    {
#if PYTHON_VERSION < 300
        _sentinel_value = PyCObject_FromVoidPtr( NULL, NULL );
#else
        // The NULL value is not allowed for a capsule, so use something else.
        _sentinel_value = PyCapsule_New( (void *)27, "sentinel", NULL );
#endif
        assert( _sentinel_value );

        __initConstants();
    }
}
